---
abstract: 'log to FirePHP via an PerlIO layer'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PerlIO-via-ToFirePHP
provides:
  PerlIO::via::ToFirePHP:
    file: lib/PerlIO/via/ToFirePHP.pm
    version: 1.100860
requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  FirePHP::Dispatcher: 0
  HTTP::Headers: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=PerlIO-via-ToFirePHP
  homepage: http://search.cpan.org/dist/PerlIO-via-ToFirePHP/
  repository: http://github.com/hanekomu/PerlIO-via-ToFirePHP
version: 1.100860
